In [ ]:
import sys
import os
sys.path.append(os.path.abspath(".."))
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from src.data.load_data import load_raw_data
from src.data.clean_data import clean_basic
from src.features.build_features import get_da_data,get_ds_data

In [2]:
df=load_raw_data()
df.head(10)

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
5,18189371,Din Tai Fung,162,Mandaluyong City,"Ground Floor, Mega Fashion Hall, SM Megamall, ...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056314,14.583764,Chinese,...,Botswana Pula(P),No,No,No,No,3,4.4,Green,Very Good,336
6,6300781,Buffet 101,162,Pasay City,"Building K, SM By The Bay, Sunset Boulevard, M...","SM by the Bay, Mall of Asia Complex, Pasay City","SM by the Bay, Mall of Asia Complex, Pasay Cit...",120.979667,14.531333,"Asian, European",...,Botswana Pula(P),Yes,No,No,No,4,4.0,Green,Very Good,520
7,6301290,Vikings,162,Pasay City,"Building B, By The Bay, Seaside Boulevard, Mal...","SM by the Bay, Mall of Asia Complex, Pasay City","SM by the Bay, Mall of Asia Complex, Pasay Cit...",120.979333,14.540000,"Seafood, Filipino, Asian, European",...,Botswana Pula(P),Yes,No,No,No,4,4.2,Green,Very Good,677
8,6300010,Spiral - Sofitel Philippine Plaza Manila,162,Pasay City,"Plaza Level, Sofitel Philippine Plaza Manila, ...","Sofitel Philippine Plaza Manila, Pasay City","Sofitel Philippine Plaza Manila, Pasay City, P...",120.980090,14.552990,"European, Asian, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.9,Dark Green,Excellent,621
9,6314987,Locavore,162,Pasig City,"Brixton Technology Center, 10 Brixton Street, ...",Kapitolyo,"Kapitolyo, Pasig City",121.056532,14.572041,Filipino,...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,532

In [3]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   str
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   str
 4   Address               9551 non-null   str
 5   Locality              9551 non-null   str
 6   Locality Verbose      9551 non-null   str
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   str
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   str
 12  Has Table booking     9551 non-null   str
 13  Has Online delivery   9551 non-null   str
 14  Is delivering now     9551 non-null   str
 15  Switch to order menu  9551 non-null   str
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   str
 19  Rating text           9551 non-null   str
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), str(13)
memory usage: 3.1 MB

,Restaurant ID,Country Code,Longitude,Latitude,Average Cost for two,Price range,Aggregate rating,Votes
count,9.551000e+03,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000
mean,9.051128e+06,18.365616,64.126574,25.854381,1199.210763,1.804837,2.666370,156.909748
std,8.791521e+06,56.750546,41.467058,11.007935,16121.183073,0.905609,1.516378,430.169145
min,5.300000e+01,1.000000,-157.948486,-41.330428,0.000000,1.000000,0.000000,0.000000
25%,3.019625e+05,1.000000,77.081343,28.478713,250.000000,1.000000,2.500000,5.000000
50%,6.004089e+06,1.000000,77.191964,28.570469,400.000000,2.000000,3.200000,31.000000
75%,1.835229e+07,1.000000,77.282006,28.642758,700.000000,2.000000,3.700000,131.000000
max,1.850065e+07,216.000000,174.832089,55.976980,800000.000000,4.000000,4.900000,10934.000000

In [4]:
df_basic_clean=clean_basic(df)
df_basic_clean.head(10)

 Cleaning data...
-> Clean hoàn tất, kích thước dữ liệu hiện tại: (9551, 21)

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Price range,Aggregate rating,Rating color,Rating text,Votes,Country
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,3,4.8,Dark Green,Excellent,314,Phillipines
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,3,4.5,Dark Green,Excellent,591,Phillipines
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,4,4.4,Green,Very Good,270,Phillipines
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,4,4.9,Dark Green,Excellent,365,Phillipines
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,4,4.8,Dark Green,Excellent,229,Phillipines
5,18189371,Din Tai Fung,162,Mandaluyong City,"Ground Floor, Mega Fashion Hall, SM Megamall, ...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056314,14.583764,Chinese,...,Botswana Pula(P),No,No,No,3,4.4,Green,Very Good,336,Phillipines
6,6300781,Buffet 101,162,Pasay City,"Building K, SM By The Bay, Sunset Boulevard, M...","SM by the Bay, Mall of Asia Complex, Pasay City","SM by the Bay, Mall of Asia Complex, Pasay Cit...",120.979667,14.531333,"Asian, European",...,Botswana Pula(P),Yes,No,No,4,4.0,Green,Very Good,520,Phillipines
7,6301290,Vikings,162,Pasay City,"Building B, By The Bay, Seaside Boulevard, Mal...","SM by the Bay, Mall of Asia Complex, Pasay City","SM by the Bay, Mall of Asia Complex, Pasay Cit...",120.979333,14.540000,"Seafood, Filipino, Asian, European",...,Botswana Pula(P),Yes,No,No,4,4.2,Green,Very Good,677,Phillipines
8,6300010,Spiral - Sofitel Philippine Plaza Manila,162,Pasay City,"Plaza Level, Sofitel Philippine Plaza Manila, ...","Sofitel Philippine Plaza Manila, Pasay City","Sofitel Philippine Plaza Manila, Pasay City, P...",120.980090,14.552990,"European, Asian, Indian",...,Botswana Pula(P),Yes,No,No,4,4.9,Dark Green,Excellent,621,Phillipines
9,6314987,Locavore,162,Pasig City,"Brixton Technology Center, 10 Brixton Street, ...",Kapitolyo,"Kapitolyo, Pasig City",121.056532,14.572041,Filipino,...,Botswana Pula(P),Yes,No,No,3,4.8,Dark Green,Excellent,532,Phillipines

In [5]:
df_basic_clean.info()
df_basic_clean.describe()

<class 'pandas.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   str
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   str
 4   Address               9551 non-null   str
 5   Locality              9551 non-null   str
 6   Locality Verbose      9551 non-null   str
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9551 non-null   str
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   str
 12  Has Table booking     9551 non-null   str
 13  Has Online delivery   9551 non-null   str
 14  Is delivering now     9551 non-null   str
 15  Price range           9551 non-null   int64
 16  Aggregate rating      9551 non-null   float64
 17  Rating color          9551 non-null   str
 18  Rating text           9551 non-null   str
 19  Votes                 9551 non-null   int64
 20  Country               9551 non-null   str
dtypes: float64(3), int64(5), str(13)
memory usage: 3.2 MB

,Restaurant ID,Country Code,Longitude,Latitude,Average Cost for two,Price range,Aggregate rating,Votes
count,9.551000e+03,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000
mean,9.051128e+06,18.365616,64.126574,25.854381,1199.210763,1.804837,2.666370,156.909748
std,8.791521e+06,56.750546,41.467058,11.007935,16121.183073,0.905609,1.516378,430.169145
min,5.300000e+01,1.000000,-157.948486,-41.330428,0.000000,1.000000,0.000000,0.000000
25%,3.019625e+05,1.000000,77.081343,28.478713,250.000000,1.000000,2.500000,5.000000
50%,6.004089e+06,1.000000,77.191964,28.570469,400.000000,2.000000,3.200000,31.000000
75%,1.835229e+07,1.000000,77.282006,28.642758,700.000000,2.000000,3.700000,131.000000
max,1.850065e+07,216.000000,174.832089,55.976980,800000.000000,4.000000,4.900000,10934.000000

In [6]:
df_basic_clean["Country"].value_counts()

Country
India             8652
United States      434
United Kingdom      80
Brazil              60
UAE                 60
South Africa        60
New Zealand         40
Turkey              34
Australia           24
Phillipines         22
Indonesia           21
Singapore           20
Qatar               20
Sri Lanka           20
Canada               4
Name: count, dtype: int64

In [7]:
df_clean=get_da_data(df)
df_clean.head(10)

--- DA Feature Engineering
 Cleaning data...
-> Clean hoàn tất, kích thước dữ liệu hiện tại: (9551, 21)
-> Hoàn tất xử lí dữ liệu DA. Kích thước: (9551, 18)

,Restaurant Name,City,Address,Locality,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Price range,Aggregate rating,Rating color,Rating text,Votes,Country
0,Le Petit Souffle,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City",121.027535,14.565443,"French, Japanese, Desserts",1100,Botswana Pula(P),Yes,No,No,3,4.8,Dark Green,Excellent,314,Phillipines
1,Izakaya Kikufuji,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City",121.014101,14.553708,Japanese,1200,Botswana Pula(P),Yes,No,No,3,4.5,Dark Green,Excellent,591,Phillipines
2,Heat - Edsa Shangri-La,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),Yes,No,No,4,4.4,Green,Very Good,270,Phillipines
3,Ooma,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City",121.056475,14.585318,"Japanese, Sushi",1500,Botswana Pula(P),No,No,No,4,4.9,Dark Green,Excellent,365,Phillipines
4,Sambo Kojin,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City",121.057508,14.584450,"Japanese, Korean",1500,Botswana Pula(P),Yes,No,No,4,4.8,Dark Green,Excellent,229,Phillipines
5,Din Tai Fung,Mandaluyong City,"Ground Floor, Mega Fashion Hall, SM Megamall, ...","SM Megamall, Ortigas, Mandaluyong City",121.056314,14.583764,Chinese,1000,Botswana Pula(P),No,No,No,3,4.4,Green,Very Good,336,Phillipines
6,Buffet 101,Pasay City,"Building K, SM By The Bay, Sunset Boulevard, M...","SM by the Bay, Mall of Asia Complex, Pasay City",120.979667,14.531333,"Asian, European",2000,Botswana Pula(P),Yes,No,No,4,4.0,Green,Very Good,520,Phillipines
7,Vikings,Pasay City,"Building B, By The Bay, Seaside Boulevard, Mal...","SM by the Bay, Mall of Asia Complex, Pasay City",120.979333,14.540000,"Seafood, Filipino, Asian, European",2000,Botswana Pula(P),Yes,No,No,4,4.2,Green,Very Good,677,Phillipines
8,Spiral - Sofitel Philippine Plaza Manila,Pasay City,"Plaza Level, Sofitel Philippine Plaza Manila, ...","Sofitel Philippine Plaza Manila, Pasay City",120.980090,14.552990,"European, Asian, Indian",6000,Botswana Pula(P),Yes,No,No,4,4.9,Dark Green,Excellent,621,Phillipines
9,Locavore,Pasig City,"Brixton Technology Center, 10 Brixton Street, ...",Kapitolyo,121.056532,14.572041,Filipino,1100,Botswana Pula(P),Yes,No,No,3,4.8,Dark Green,Excellent,532,Phillipines

In [8]:
df_clean.info()
df_clean.describe()

<class 'pandas.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant Name       9551 non-null   str
 1   City                  9551 non-null   str
 2   Address               9551 non-null   str
 3   Locality              9551 non-null   str
 4   Longitude             9551 non-null   float64
 5   Latitude              9551 non-null   float64
 6   Cuisines              9551 non-null   str
 7   Average Cost for two  9551 non-null   int64
 8   Currency              9551 non-null   str
 9   Has Table booking     9551 non-null   str
 10  Has Online delivery   9551 non-null   str
 11  Is delivering now     9551 non-null   str
 12  Price range           9551 non-null   int64
 13  Aggregate rating      9551 non-null   float64
 14  Rating color          9551 non-null   str
 15  Rating text           9551 non-null   str
 16  Votes                 9551 non-null   int64
 17  Country               9551 non-null   str
dtypes: float64(3), int64(3), str(12)
memory usage: 2.7 MB

,Longitude,Latitude,Average Cost for two,Price range,Aggregate rating,Votes
count,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000
mean,64.126574,25.854381,1199.210763,1.804837,2.666370,156.909748
std,41.467058,11.007935,16121.183073,0.905609,1.516378,430.169145
min,-157.948486,-41.330428,0.000000,1.000000,0.000000,0.000000
25%,77.081343,28.478713,250.000000,1.000000,2.500000,5.000000
50%,77.191964,28.570469,400.000000,2.000000,3.200000,31.000000
75%,77.282006,28.642758,700.000000,2.000000,3.700000,131.000000
max,174.832089,55.976980,800000.000000,4.000000,4.900000,10934.000000

In [13]:
df_ds_train,df_ds_test=get_ds_data(df)
df_ds_train.head(10)

--- DS Feature Engineering
 Cleaning data...
-> Clean hoàn tất, kích thước dữ liệu hiện tại: (9551, 21)
-> Hoàn tất xử lí dữ liệu DS. Train: 7403 dòng | Test: 2148 dòng

,City,Longitude,Latitude,Cuisines,Average Cost for two,Has Table booking,Has Online delivery,Is delivering now,Price range,Aggregate rating,...,Currency_Dollar($),Currency_Emirati Diram(AED),Currency_Indian Rupees(Rs.),Currency_Indonesian Rupiah(IDR),Currency_NewZealand($),Currency_Pounds(£),Currency_Qatari Rial(QR),Currency_Rand(R),Currency_Sri Lankan Rupee(LKR),Currency_Turkish Lira(TL)
0,0.000209,121.027535,14.565443,0.000105,1100,Yes,No,No,3,4.8,...,0,0,0,0,0,0,0,0,0,0
1,0.000209,121.014101,14.553708,0.001780,1200,Yes,No,No,3,4.5,...,0,0,0,0,0,0,0,0,0,0
2,0.000419,121.056831,14.581404,0.000105,4000,Yes,No,No,4,4.4,...,0,0,0,0,0,0,0,0,0,0
3,0.000419,121.056475,14.585318,0.001885,1500,No,No,No,4,4.9,...,0,0,0,0,0,0,0,0,0,0
4,0.000419,121.057508,14.584450,0.000314,1500,Yes,No,No,4,4.8,...,0,0,0,0,0,0,0,0,0,0
5,0.000419,121.056314,14.583764,0.037064,1000,No,No,No,3,4.4,...,0,0,0,0,0,0,0,0,0,0
6,0.000314,120.979667,14.531333,0.000209,2000,Yes,No,No,4,4.0,...,0,0,0,0,0,0,0,0,0,0
7,0.000314,120.979333,14.540000,0.000105,2000,Yes,No,No,4,4.2,...,0,0,0,0,0,0,0,0,0,0
8,0.000314,120.980090,14.552990,0.000105,6000,Yes,No,No,4,4.9,...,0,0,0,0,0,0,0,0,0,0
9,0.000314,121.056532,14.572041,0.000314,1100,Yes,No,No,3,4.8,...,0,0,0,0,0,0,0,0,0,0

In [16]:
df_ds_train.info()
df_ds_train.describe()

<class 'pandas.DataFrame'>
Index: 7403 entries, 0 to 9550
Data columns (total 23 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   City                             7403 non-null   float64
 1   Longitude                        7403 non-null   float64
 2   Latitude                         7403 non-null   float64
 3   Cuisines                         7403 non-null   float64
 4   Average Cost for two             7403 non-null   int64
 5   Has Table booking                7403 non-null   str
 6   Has Online delivery              7403 non-null   str
 7   Is delivering now                7403 non-null   str
 8   Price range                      7403 non-null   int64
 9   Aggregate rating                 7403 non-null   float64
 10  Votes                            7403 non-null   int64
 11  Country                          7403 non-null   str
 12  Currency_Brazilian Real(R$)      7403 non-null   int64
 13  Currency_Dollar($)               7403 non-null   int64
 14  Currency_Emirati Diram(AED)      7403 non-null   int64
 15  Currency_Indian Rupees(Rs.)      7403 non-null   int64
 16  Currency_Indonesian Rupiah(IDR)  7403 non-null   int64
 17  Currency_NewZealand($)           7403 non-null   int64
 18  Currency_Pounds(£)              7403 non-null   int64
 19  Currency_Qatari Rial(QR)         7403 non-null   int64
 20  Currency_Rand(R)                 7403 non-null   int64
 21  Currency_Sri Lankan Rupee(LKR)   7403 non-null   int64
 22  Currency_Turkish Lira(TL)        7403 non-null   int64
dtypes: float64(5), int64(14), str(4)
memory usage: 1.4 MB

,City,Longitude,Latitude,Cuisines,Average Cost for two,Price range,Aggregate rating,Votes,Currency_Brazilian Real(R$),Currency_Dollar($),Currency_Emirati Diram(AED),Currency_Indian Rupees(Rs.),Currency_Indonesian Rupiah(IDR),Currency_NewZealand($),Currency_Pounds(£),Currency_Qatari Rial(QR),Currency_Rand(R),Currency_Sri Lankan Rupee(LKR),Currency_Turkish Lira(TL)
count,7403.000000,7403.000000,7403.000000,7403.000000,7403.000000,7403.000000,7403.000000,7403.000000,7403.000000,7403.000000,7403.000000,7403.000000,7403.000000,7403.000000,7403.000000,7403.000000,7403.000000,7403.000000,7403.000000
mean,0.339010,63.462859,26.182970,0.017601,1448.415102,1.970147,3.440024,202.185060,0.007429,0.064703,0.008105,0.879778,0.002837,0.005403,0.010671,0.002702,0.008105,0.002702,0.004593
std,0.259799,44.696549,11.267380,0.026303,18303.524265,0.930611,0.552195,479.195199,0.085879,0.246019,0.089667,0.325242,0.053189,0.073313,0.102756,0.051910,0.089667,0.051910,0.067618
min,0.000105,-157.948486,-41.330428,0.000105,0.000000,1.000000,1.800000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.113077,77.082416,28.475505,0.000419,300.000000,1.000000,3.000000,19.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.573029,77.191784,28.570000,0.005549,500.000000,2.000000,3.400000,60.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.573029,77.272293,28.645259,0.031306,800.000000,3.000000,3.800000,181.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,0.573029,174.832089,55.976980,0.098000,800000.000000,4.000000,4.900000,10934.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [19]:
df_ds_train["Aggregate rating"].value_counts()

Aggregate rating
3.2    522
3.1    519
3.4    498
3.3    483
3.5    480
3.0    468
3.6    458
3.7    427
3.8    400
2.9    381
3.9    335
2.8    315
4.1    274
4.0    266
2.7    250
4.2    221
2.6    191
4.3    174
4.4    144
2.5    110
4.5     95
2.4     87
4.6     78
4.9     61
2.3     47
4.7     42
2.2     27
4.8     25
2.1     15
2.0      7
1.9      2
1.8      1
Name: count, dtype: int64

In [22]:
df_ds_test["Aggregate rating"].value_counts()

Aggregate rating
0.0    2148
Name: count, dtype: int64

In [15]:
print(df.shape)
print(df_clean.shape)
print(df_ds_train.shape)
df_ds_test.shape

(9551, 21)
(9551, 18)
(7403, 23)

(2148, 23)

In [ ]:
# dữ liệu thiếu
df.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [ ]:
#dữ liệu trùng lặp
df.duplicated().sum()

np.int64(0)

In [ ]:
categorical_cols = df_basic_clean.select_dtypes(include=['object', 'str']).columns

print(f"Tổng số cột dạng chuỗi cần kiểm tra: {len(categorical_cols)}")

for col in categorical_cols:
    print(f"--- Kiểm tra cột: {col} ---")
    print(f"Số lượng giá trị duy nhất: {df_basic_clean[col].nunique()}")
    
    values=df_basic_clean[col].dropna().astype(str).unique()
    print(f"Các giá trị xuất hiện: {sorted(values)[:20]}")
    print("\n")

Tổng số cột dạng chuỗi cần kiểm tra: 13
--- Kiểm tra cột: Restaurant Name ---
Số lượng giá trị duy nhất: 7446
Các giá trị xuất hiện: ['#45', '#Dilliwaala6', '#InstaFreeze', '#OFF Campus', '#Urban Cafí©', '#hashtag', "'Ohana", '10 Downing Street', '10 To 10 In Delhi', '11th Avenue Cafe Bistro', '12212', '13 Cafe', '145 Kala Ghoda', '17 Degree Food Service', '17 Degrees', '18 Degrees Resto Lounge', '19 Flavours Biryani', '1911 - The Imperial', '1911 Bar - The Imperial', '1918 Bistro & Grill']


--- Kiểm tra cột: City ---
Số lượng giá trị duy nhất: 141
Các giá trị xuất hiện: ['Abu Dhabi', 'Agra', 'Ahmedabad', 'Albany', 'Allahabad', 'Amritsar', 'Ankara', 'Armidale', 'Athens', 'Auckland', 'Augusta', 'Aurangabad', 'Balingup', 'Bandung', 'Bangalore', 'Beechworth', 'Bhopal', 'Bhubaneshwar', 'Birmingham', 'Bogor']


--- Kiểm tra cột: Address ---
Số lượng giá trị duy nhất: 8918
Các giá trị xuất hiện: ['1 & 2, Block A-5 B, DDA Market, Paschim Vihar, New Delhi', '1 & 2, C-5A, Kadimi Market, Janakpuri, New Delhi', '1 & 2, Krishna Royal Plaza, Alfa Commercial Belt 1, Greater Noida, Noida', '1 & 2, Lal Sai Market, Lajpat Nagar 2, New Delhi', '1 & 2, Living Style Mall, Main Kalindi Kunj Road, Jasola, New Delhi', '1 & 21 KD, Ground Floor, DDA Market, Pitampura, New Delhi', '1 & 3, Main Market, Uday Park, New Delhi', '1 & 4, L Block Market, Behind Metro Hospital, Sector 11, Noida', '1 Canal Square, Brindleyplace, Birmingham B16 8EH', '1 Fox Street, Marshalltown, Inner City, Johannesburg', '1 Leven Street, Tollcross, Edinburgh EH3 9NB', '1 Rocklands Avenue, Balmoral, Auckland', '1, A Block Market, Preet Vihar, New Delhi', '1, A Block Market, Shalimar Bagh, New Delhi', '1, A-4, Gole DDA Market, Paschim Vihar, New Delhi', '1, Anangpur Chowk, Opposite Omaxe Forest & Spa, Suraj Kund, Faridabad', '1, Ashoka Road, Feroze Shah Road, New Delhi', '1, Assam Bhavan, Chanakyapuri, New Delhi', '1, Awadhpuri, Near Kailash Mall, Lal Kothi, Jaipur Lal Kothi', '1, Balewadi High Street, Cummins India Office Campus, Baner-Balewadi Link Road, Pune']


--- Kiểm tra cột: Locality ---
Số lượng giá trị duy nhất: 1208
Các giá trị xuất hiện: ['12th Square Building, Banjara Hills', 'A Hotel, Gurdev Nagar', 'ARSS Mall, Paschim Vihar', 'Aaya Nagar', 'Abu Dhabi Mall, Tourist Club Area  (Al Zahiyah)', 'Abu Shagara', 'Acropolis Mall, Kasba', 'Adajan Gam', 'Adchini', 'Addition Hills', 'Aditya Mega Mall, Karkardooma', 'Adyar', 'Aerocity', 'Aggar Nagar', 'Aggarwal City Mall, Pitampura', 'Aggarwal City Plaza, Rohini', 'Agra Cantt', 'Ain Khalid', 'Akashwani', 'Al Barari']


--- Kiểm tra cột: Locality Verbose ---
Số lượng giá trị duy nhất: 1265
Các giá trị xuất hiện: ['12th Square Building, Banjara Hills, Hyderabad', 'A Hotel, Gurdev Nagar, Ludhiana', 'ARSS Mall, Paschim Vihar, New Delhi', 'Aaya Nagar, New Delhi', 'Abu Dhabi Mall, Tourist Club Area  (Al Zahiyah), Abu Dhabi', 'Abu Shagara, Sharjah', 'Acropolis Mall, Kasba , Kolkata', 'Adajan Gam, Surat', 'Adchini, New Delhi', 'Addition Hills, San Juan City', 'Aditya Mega Mall, Karkardooma, New Delhi', 'Adyar, Chennai', 'Aerocity, New Delhi', 'Aggar Nagar, Ludhiana', 'Aggarwal City Mall, Pitampura, New Delhi', 'Aggarwal City Plaza, Rohini, New Delhi', 'Agra Cantt, Agra', 'Ain Khalid, Doha', 'Akashwani, Aurangabad', 'Al Barari, Dubai']


--- Kiểm tra cột: Cuisines ---
Số lượng giá trị duy nhất: 1826
Các giá trị xuất hiện: ['Afghani', 'Afghani, Mughlai, Chinese', 'Afghani, North Indian', 'Afghani, North Indian, Pakistani, Arabian', 'African', 'African, Portuguese', 'American', 'American, Asian, Burger', 'American, Asian, European, Seafood', 'American, Asian, Italian, Seafood', 'American, Asian, North Indian, Mexican, South Indian', 'American, BBQ', 'American, BBQ, Burger', 'American, BBQ, Sandwich', 'American, BBQ, Seafood', 'American, BBQ, Southern', 'American, BBQ, Steak', 'American, Bakery, European, Burger, Fusion', 'American, Bar Food', 'American, Bar Food, BBQ']


--- Kiểm tra cột: Currency ---
Số lượng giá trị duy nhất: 12
Các giá trị xuất hiện: ['Botswana Pula(P)', 'Brazilian Real(R$)', 'Dollar($)', 'Emirati Diram(AED)', 'Indian Rupees(Rs.)', 'Indonesian Rupiah(IDR)', 'NewZealand($)', 'Pounds(\x8c£)', 'Qatari Rial(QR)', 'Rand(R)', 'Sri Lankan Rupee(LKR)', 'Turkish Lira(TL)']


--- Kiểm tra cột: Has Table booking ---
Số lượng giá trị duy nhất: 2
Các giá trị xuất hiện: ['No', 'Yes']


--- Kiểm tra cột: Has Online delivery ---
Số lượng giá trị duy nhất: 2
Các giá trị xuất hiện: ['No', 'Yes']


--- Kiểm tra cột: Is delivering now ---
Số lượng giá trị duy nhất: 2
Các giá trị xuất hiện: ['No', 'Yes']


--- Kiểm tra cột: Rating color ---
Số lượng giá trị duy nhất: 6
Các giá trị xuất hiện: ['Dark Green', 'Green', 'Orange', 'Red', 'White', 'Yellow']


--- Kiểm tra cột: Rating text ---
Số lượng giá trị duy nhất: 6
Các giá trị xuất hiện: ['Average', 'Excellent', 'Good', 'Not rated', 'Poor', 'Very Good']


--- Kiểm tra cột: Country ---
Số lượng giá trị duy nhất: 15
Các giá trị xuất hiện: ['Australia', 'Brazil', 'Canada', 'India', 'Indonesia', 'New Zealand', 'Phillipines', 'Qatar', 'Singapore', 'South Africa', 'Sri Lanka', 'Turkey', 'UAE', 'United Kingdom', 'United States']